### ISSUE TITLE
how mac layer get RSSI from phy layer

### ISSUE THREAD

**Issue by xxxxxy211** [LLusvarghi/MoReV2X#3]
I am trying to modify the MoReV2X simulator to integrate with ns3-gym.

I want the MAC layer to pass the RSSI information of the CSR to ns3-gym when selecting resources. I noticed that nr-v2x-ue-phy.cc contains struct RSSImeas to store the RSSI value, and in nr-v2x-ue-mac.cc, struct CandidateCSRl2 saves the RSSI value, and std::vector<CandidateCSRl2> finalL2 saves the CSRs used for random selection. But before these CandidateCSRl2 FinalL2tmpItem are added to finalL2, their RSSI are all set to 0.
I want to know why this is done? And how can I get the RSSI value of each CSR in finalL2 at the MAC layer? 

In addition, I also observed that your TO DO FIX item contains a work on the transmission of the RSRP value of the physical layer. What is the difficulty in developing this work? (I don’t know much about the knowledge of these communication bottom layers)

**Comment by LLusvarghi** [comment]
Hi Chen, 

The RSSIs are all set to zero because in NR-V2X Mode 2 the RSSI measurements are no longer used during the resource reselection process. This is one of the main differences of NR-V2X Mode 2 with respect to its LTE-V2X Mode 4 predecessor. 
The PHY layer is already in charge of passing the RSRP values to the MAC layer, as the RSRP values are used by NR-V2X Mode 2 to identify candidate resources. You could follow the same procedure that is used for the RSRP to report the RSSI measurements to the MAC layer.

**Comment by xxxxxy211** [comment]
thanks for your help！I got it.

**Comment by xxxxxy211** [comment]
Thank you very much for your help, I figured it out.
